---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-central
  namespace: kube-system
  labels:
    component: fluentd-central
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fluentd-central
  labels:
    component: fluentd-central
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods"]
  verbs: ["get", "watch", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fluentd-central
  labels:
    component: fluentd-central
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: fluentd-central
  namespace: kube-system
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: fluentd-central
  apiGroup: ""

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: central-fluentd-deployment
  namespace: kube-system
spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: fluentd-central 
        app: log_app
    spec:
      serviceAccountName: fluentd-central
      containers:
      - name: central-fluentd-deployment
        image: quay.io/samsung_cnct/fluentd-central
        ports:
        - containerPort: 80